// ==UserScript==
// @name         Yahoo Fantasy Draft Assistant — MFL
// @namespace    https://github.com/Bean0-0/fantasy-football
// @version      0.6.1
// @description  Live draft assistant tuned for MFL league: 10-team, 0.5 PPR, snake draft, 16 rounds
// @match        https://football.fantasysports.yahoo.com/*
// @updateURL    https://raw.githubusercontent.com/Bean0-0/fantasy-football/master/userscript/fantasy-draft-assistant.user.js
// @downloadURL  https://raw.githubusercontent.com/Bean0-0/fantasy-football/master/userscript/fantasy-draft-assistant.user.js
// @grant        none
// @run-at       document-idle
// @require      https://raw.githubusercontent.com/Bean0-0/fantasy-football/master/userscript/board.js
// ==/UserScript==

(function () {
  "use strict";

  /* ============================================================
   * LEAGUE CONFIG — MFL (Meemaw Football League), ID 1306729
   * 10 teams · 0.5 PPR · snake · 16 rounds · 45s pick timer
   * Starters: QB, WR, WR, RB, RB, TE, W/R/T, K, DEF + 6 BN
   * ============================================================ */
  const TEAMS = 10;
  const ROUNDS = 16;

  // Roster targets across 16 picks (bench depth included)
  const ROSTER_TARGETS = { QB: 1, RB: 5, WR: 6, TE: 2, K: 1, DEF: 1 };
  // Starters per position (flex counted separately)
  const STARTERS = { QB: 1, RB: 2, WR: 2, TE: 1, K: 1, DEF: 1 };

  /* BOARD loaded via @require from userscript/board.js (generated by src/build_board.py) */

  /* ================= STATE ================= */
  const drafted = new Set(JSON.parse(localStorage.getItem("fda_drafted") || "[]"));
  const myPicks = new Set(JSON.parse(localStorage.getItem("fda_mypicks") || "[]"));
  let mySlot = parseInt(localStorage.getItem("fda_slot") || "0", 10); // 1-10, 0 = unset
  const save = () => {
    localStorage.setItem("fda_drafted", JSON.stringify([...drafted]));
    localStorage.setItem("fda_mypicks", JSON.stringify([...myPicks]));
    localStorage.setItem("fda_slot", String(mySlot));
  };

  const available = () => BOARD.filter((p) => !drafted.has(p[1]));

  /* Snake draft math: overall pick numbers I own */
  function myOverallPicks(slot) {
    const picks = [];
    for (let r = 1; r <= ROUNDS; r++) {
      picks.push(r % 2 === 1 ? (r - 1) * TEAMS + slot : r * TEAMS - slot + 1);
    }
    return picks;
  }

  function nextMyPick() {
    if (!mySlot) return null;
    const taken = drafted.size;
    return myOverallPicks(mySlot).find((n) => n > taken) ?? null;
  }

  /* Availability odds: P(player still there at my next pick).
     Logistic on gap between player's ADP and my next overall pick. */
  function availOdds(adp) {
    const next = nextMyPick();
    if (!next) return null;
    const gap = next - adp;
    return Math.round(100 / (1 + Math.exp(-gap / 3.5)));
  }

  /* Position counting for my roster (flex-eligible overflow counts) */
  function myPosCount(pos) {
    return BOARD.filter((p) => myPicks.has(p[1]) && p[2] === pos).length;
  }

  function needScore(pos) {
    return Math.max(0, (ROSTER_TARGETS[pos] ?? 0) - myPosCount(pos));
  }

  /* Recommendation score: rank, boosted if position needed, penalized K/DEF early */
  function recScore(p, pickNum) {
    const [rank, , pos] = [p[0], p[1], p[2]];
    let s = 1000 - rank * 6;
    if (needScore(pos) > 0) s += 25;
    if ((pos === "K" || pos === "DEF") && pickNum && pickNum <= (ROUNDS - 2) * TEAMS) s -= 500;
    if (pos === "QB" && myPosCount("QB") >= 1 && pickNum && pickNum < 80) s -= 40;
    if (pos === "TE" && myPosCount("TE") >= 1 && pickNum && pickNum < 60) s -= 30;
    return s;
  }

  /* ================= UI ================= */
  const panel = document.createElement("div");
  panel.id = "fda-panel";
  panel.innerHTML = `
    <div id="fda-header">
      <strong>Draft Assistant</strong>
      <span id="fda-count"></span>
      <button id="fda-min">–</button>
    </div>
    <div id="fda-body">
      <div id="fda-slotrow">My draft slot:
        <select id="fda-slot"><option value="0">set me</option></select>
        <span id="fda-next"></span>
      </div>
      <div id="fda-rec"></div>
      <div id="fda-needs"></div>
      <table id="fda-table">
        <thead><tr><th>#</th><th>Player</th><th>Pos</th><th>Bye</th><th>Avail%</th><th></th></tr></thead>
        <tbody></tbody>
      </table>
      <div id="fda-actions">
        <button id="fda-undo">Undo</button>
        <button id="fda-reset">Reset</button>
      </div>
    </div>`;
  document.body.appendChild(panel);

  const style = document.createElement("style");
  style.textContent = `
    #fda-panel { position: fixed; top: 80px; right: 16px; width: 320px; z-index: 99999;
      background: #1b1f24; color: #eee; border: 1px solid #444; border-radius: 8px;
      font: 13px/1.4 -apple-system, sans-serif; box-shadow: 0 4px 16px rgba(0,0,0,.5); }
    #fda-header { display: flex; justify-content: space-between; align-items: center;
      padding: 8px 10px; cursor: move; background: #262b33; border-radius: 8px 8px 0 0; }
    #fda-header button { background: none; border: none; color: #eee; font-size: 16px; cursor: pointer; }
    #fda-count, #fda-next { font-size: 11px; color: #9ab; }
    #fda-body { max-height: 62vh; overflow-y: auto; padding: 6px; }
    #fda-body.fda-hidden { display: none; }
    #fda-slotrow { padding: 2px 4px 6px; font-size: 12px; color: #9ab; }
    #fda-slot { background: #2d333b; color: #eee; border: 1px solid #555; border-radius: 4px; }
    #fda-rec { padding: 6px; margin: 2px 4px 6px; background: #1e3a24; border: 1px solid #2e7d43;
      border-radius: 6px; font-weight: 600; font-size: 13px; }
    #fda-rec small { display: block; font-weight: 400; color: #9cb; }
    #fda-needs { padding: 2px 6px 6px; font-size: 11px; color: #b8c; }
    #fda-table { width: 100%; border-collapse: collapse; }
    #fda-table th { text-align: left; color: #89a; font-size: 11px; padding: 2px 4px; }
    #fda-table td { padding: 3px 4px; border-top: 1px solid #2c333c; }
    #fda-table tr.fda-need { background: #24311f; }
    #fda-table tr.fda-top { background: #1e3a24; }
    .fda-odds-hi { color: #6f6; } .fda-odds-md { color: #fc6; } .fda-odds-lo { color: #f66; }
    #fda-table .fda-btn { font-size: 10px; cursor: pointer; border: 1px solid #555;
      border-radius: 4px; background: #333; color: #ddd; padding: 1px 5px; margin-right: 3px; }
    #fda-actions { display: flex; gap: 6px; padding: 8px 4px; }
    #fda-actions button { flex: 1; background: #2d333b; color: #ddd; border: 1px solid #555;
      border-radius: 5px; padding: 4px; cursor: pointer; font-size: 11px; }`;
  document.head.appendChild(style);

  const slotSel = panel.querySelector("#fda-slot");
  for (let i = 1; i <= TEAMS; i++) {
    const o = document.createElement("option");
    o.value = String(i);
    o.textContent = `Pick ${i}`;
    slotSel.appendChild(o);
  }
  slotSel.value = String(mySlot);
  slotSel.addEventListener("change", () => {
    mySlot = parseInt(slotSel.value, 10);
    save();
    render();
  });

  /* ================= RENDER ================= */
  function render() {
    const tbody = panel.querySelector("#fda-table tbody");
    const avail = available();
    const next = nextMyPick();

    const ranked = avail
      .map((p) => ({ p, s: recScore(p, next) }))
      .sort((a, b) => b.s - a.s);
    const rec = ranked[0]?.p;
    const rec2 = ranked[1]?.p;

    panel.querySelector("#fda-rec").innerHTML = rec
      ? `▶ Suggested: ${rec[1]} (${rec[2]}, ${rec[3]})` +
        (rec2 ? `<small>backup: ${rec2[1]} (${rec2[2]})</small>` : "")
      : "▶ Board empty";

    panel.querySelector("#fda-next").textContent = next
      ? `· you pick @ #${next}`
      : "";

    const needs = Object.keys(ROSTER_TARGETS)
      .map((pos) => (needScore(pos) > 0 ? `${pos}:${needScore(pos)}` : null))
      .filter(Boolean)
      .join("  ");
    panel.querySelector("#fda-needs").textContent = needs
      ? `Needs → ${needs}`
      : "Roster targets filled";
    panel.querySelector("#fda-count").textContent =
      `${drafted.size} drafted · ${myPicks.size} mine`;

    tbody.innerHTML = avail
      .slice(0, 18)
      .map((p) => {
        const [rank, name, pos, team, bye, , adp] = p;
        const odds = availOdds(adp);
        const oddsTxt = odds === null ? "—" : odds + "%";
        const oddsCls =
          odds === null ? "" : odds >= 70 ? "fda-odds-hi" : odds >= 40 ? "fda-odds-md" : "fda-odds-lo";
        const rowCls = rec && name === rec[1] ? ' class="fda-top"' : needScore(pos) > 0 ? ' class="fda-need"' : "";
        return `<tr${rowCls}>
          <td>${rank}</td><td>${name} <span style="color:#789">${team}</span></td>
          <td>${pos}</td><td>${bye}</td>
          <td class="${oddsCls}">${oddsTxt}</td>
          <td><button class="fda-btn" data-name="${name}" data-mine="1">me</button><button class="fda-btn" data-name="${name}" data-mine="0">gone</button></td>
        </tr>`;
      })
      .join("");

    tbody.querySelectorAll(".fda-btn").forEach((btn) =>
      btn.addEventListener("click", () => {
        drafted.add(btn.dataset.name);
        if (btn.dataset.mine === "1") myPicks.add(btn.dataset.name);
        save();
        render();
      })
    );
  }

  /* ================= CONTROLS ================= */
  panel.querySelector("#fda-undo").addEventListener("click", () => {
    const last = [...drafted].pop();
    if (last) {
      drafted.delete(last);
      myPicks.delete(last);
      save();
      render();
    }
  });
  panel.querySelector("#fda-reset").addEventListener("click", () => {
    if (confirm("Clear all draft tracking?")) {
      drafted.clear();
      myPicks.clear();
      save();
      render();
    }
  });
  panel.querySelector("#fda-min").addEventListener("click", () =>
    panel.querySelector("#fda-body").classList.toggle("fda-hidden")
  );

  const header = panel.querySelector("#fda-header");
  header.addEventListener("mousedown", (e) => {
    if (e.target.tagName === "BUTTON" || e.target.tagName === "SELECT") return;
    const dx = e.clientX - panel.offsetLeft;
    const dy = e.clientY - panel.offsetTop;
    const move = (ev) => {
      panel.style.left = ev.clientX - dx + "px";
      panel.style.top = ev.clientY - dy + "px";
      panel.style.right = "auto";
    };
    const up = () => {
      document.removeEventListener("mousemove", move);
      document.removeEventListener("mouseup", up);
    };
    document.addEventListener("mousemove", move);
    document.addEventListener("mouseup", up);
  });

  /* ================= AUTO-DETECT =================
   * New Yahoo draft client. Status bar has "Round R, Pick N" and
   * "Last: G. Pickens (WR · Dal) <ManagerName>". Poll and match.
   */
  const normTok = (s) => s.toLowerCase().replace(/[^a-z ]/g, "").trim();
  const POS_ALIAS = { DST: "DEF" };

  // match Yahoo short name ("G. Pickens", "WR", "Dal") to board row
  function matchPlayer(short, pos, team) {
    pos = POS_ALIAS[pos] || pos;
    team = team.toUpperCase();
    const m = normTok(short).match(/^([a-z])\s+(.+)$/);
    if (!m) return null;
    const [, initial, rest] = m;
    const restToks = rest.split(/\s+/);
    for (const p of BOARD) {
      const [, fullName, pPos, pTeam] = p;
      if (drafted.has(fullName)) continue;
      if (pPos !== pos || pTeam.toUpperCase() !== team) continue;
      const toks = normTok(fullName).split(/\s+/);
      if (pos === "DEF") return fullName; // team+pos enough for defenses
      if (!toks[0].startsWith(initial)) continue;
      const tail = toks.slice(-restToks.length).join(" ");
      if (tail === restToks.join(" ")) return fullName;
    }
    return null;
  }

  const picksLog = []; // {overall, short, manager, mine}
  let beepedFor = 0;

  function beep() {
    try {
      const ctx = new (window.AudioContext || window.webkitAudioContext)();
      const o = ctx.createOscillator();
      const g = ctx.createGain();
      o.connect(g); g.connect(ctx.destination);
      o.frequency.value = 880; g.gain.value = 0.15;
      o.start();
      setTimeout(() => { o.frequency.value = 1174; }, 150);
      setTimeout(() => { o.stop(); ctx.close(); }, 400);
    } catch (e) { /* audio blocked until user interaction */ }
  }

  function autoDetect() {
    // current overall pick: "Round 2, Pick 26"
    let curOverall = null, upIn = null;
    for (const sp of document.querySelectorAll("span")) {
      const t = sp.textContent || "";
      const rm = t.match(/Round\s+(\d+),\s+Pick\s+(\d+)/);
      if (rm) { curOverall = parseInt(rm[2], 10); }
      const um = t.match(/You're up in (\d+) Pick/i);
      if (um) { upIn = parseInt(um[1], 10); }
    }

    // "Last:" label -> next spans: name, (POS · Team); manager name follows
    let changed = false;
    for (const sp of document.querySelectorAll("span")) {
      if ((sp.textContent || "").trim() !== "Last:") continue;
      const nameEl = sp.nextElementSibling;
      const metaEl = nameEl && nameEl.nextElementSibling;
      if (!nameEl || !metaEl) break;
      const short = (nameEl.textContent || "").trim();
      const mm = (metaEl.textContent || "").match(/\(([A-Z]+)\s*[·\-]\s*([A-Za-z]+)\)/);
      if (!short || !mm) break;
      const managerEl = sp.closest("div")?.parentElement?.querySelector("span:last-child");
      const manager = managerEl ? managerEl.textContent.trim() : "?";

      const full = matchPlayer(short, mm[1], mm[2]);
      if (full && !drafted.has(full)) {
        const lastOverall = curOverall ? curOverall - 1 : drafted.size + 1;
        const mine = mySlot && myOverallPicks(mySlot).includes(lastOverall);
        drafted.add(full);
        if (mine) myPicks.add(full);
        picksLog.push({ overall: lastOverall, short: full, manager, mine });
        changed = true;
      }
      break;
    }

    // my-turn alarm
    if (mySlot && curOverall && myOverallPicks(mySlot).includes(curOverall) && beepedFor !== curOverall) {
      beepedFor = curOverall;
      beep();
      panel.style.border = "2px solid #4caf50";
      document.title = "\u{1F514} YOUR PICK — Yahoo Draft";
    } else if (curOverall && beepedFor && beepedFor !== curOverall) {
      panel.style.border = "1px solid #444";
    }

    if (changed) {
      save();
      render();
    }
    renderRecent(upIn);
  }

  function renderRecent(upIn) {
    let el = panel.querySelector("#fda-recent");
    if (!el) {
      el = document.createElement("div");
      el.id = "fda-recent";
      panel.querySelector("#fda-body").prepend(el);
    }
    const last = picksLog.slice(-4).reverse();
    el.innerHTML =
      (upIn != null ? `<div style="color:#8cf;font-size:11px;padding:2px 4px">You're up in ${upIn} pick${upIn === 1 ? "" : "s"}</div>` : "") +
      last.map((p) =>
        `<div style="font-size:11px;color:${p.mine ? "#6f6" : "#9ab"};padding:1px 4px">` +
        `#${p.overall} ${p.short} → ${p.manager}</div>`
      ).join("");
  }

  setInterval(autoDetect, 1500);

  render();
})();
