"""Build draft board from free sources.

Sources:
  - Sleeper API: 2026 projections (pts_half_ppr) + ADP (adp_half_ppr), no auth
  - Sleeper players DB: names, teams, bye weeks

Output:
  - data/board.json          — full merged data
  - userscript/board.js      — BOARD array to paste into userscript

MFL league: 10-team, 0.5 PPR, 16 rounds.
VORP baselines tuned for 10-team roster construction.
"""
import json
import os
import subprocess
import urllib.request

POSITIONS = ["QB", "RB", "WR", "TE", "K", "DEF"]
OUT_JSON = "data/board.json"
OUT_JS = "userscript/board.js"

# Replacement-level baselines (10-team, 1QB, 2RB, 2WR, 1TE, flex, K, DEF)
VORP_BASELINE = {"QB": 12, "RB": 30, "WR": 36, "TE": 12, "K": 10, "DEF": 10}


def fetch(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def main():
    print("Fetching Sleeper players DB...")
    players = fetch("https://api.sleeper.app/v1/players/nfl")

    print("Fetching 2026 projections...")
    all_proj = []
    for chunk in [POSITIONS[i : i + 3] for i in range(0, len(POSITIONS), 3)]:
        qs = "&".join(f"position%5B%5D={p}" for p in chunk)
        url = f"https://api.sleeper.com/projections/nfl/2026?season_type=regular&{qs}"
        all_proj.extend(fetch(url))
    print(f"  {len(all_proj)} projection rows")

    rows = []
    for pr in all_proj:
        stats = pr.get("stats") or {}
        pts = stats.get("pts_half_ppr")
        adp = stats.get("adp_half_ppr")
        if not pts or pts <= 0:
            continue
        pid = str(pr.get("player_id") or "")
        meta = players.get(pid) or {}
        pos = pr.get("position") or meta.get("fantasy_positions", [None])[0]
        if pos not in POSITIONS:
            continue

        if pos == "DEF":
            team = meta.get("team") or pid  # DEF player_id is team abbr
            name = f"{team} DST"
        else:
            name = f"{meta.get('first_name', '')} {meta.get('last_name', '')}".strip()
            team = meta.get("team") or "FA"
        if not name or name == "DST":
            name = f"{pid} DST"
            team = pid

        rows.append(
            {
                "name": name,
                "pos": pos,
                "team": team,
                "bye": pr.get("bye_week") or meta.get("bye_week") or 0,
                "proj": round(pts, 1),
                "adp": round(adp, 1) if adp and adp < 900 else None,
            }
        )

    # VORP: points above replacement at position
    vorp = {}
    for pos in POSITIONS:
        pos_rows = sorted(
            (r for r in rows if r["pos"] == pos), key=lambda r: -r["proj"]
        )
        base_idx = VORP_BASELINE[pos] - 1
        baseline = pos_rows[base_idx]["proj"] if len(pos_rows) > base_idx else 0
        for r in pos_rows:
            vorp[r["name"]] = round(r["proj"] - baseline, 1)

    for r in rows:
        r["vorp"] = vorp[r["name"]]

    # Keep draftable pool: top N per position
    LIMITS = {"QB": 20, "RB": 50, "WR": 60, "TE": 20, "K": 14, "DEF": 16}
    pool = []
    for pos in POSITIONS:
        pos_rows = sorted(
            (r for r in rows if r["pos"] == pos), key=lambda r: -r["proj"]
        )
        pool.extend(pos_rows[: LIMITS[pos]])

    # Overall rank by VORP (K/DEF forced to back — VORP tiny anyway)
    pool.sort(key=lambda r: -r["vorp"])
    for i, r in enumerate(pool, 1):
        r["rank"] = i

    # Tiers by VORP gaps
    tier, prev = 1, None
    for r in pool:
        if prev is not None and prev - r["vorp"] > 15:
            tier += 1
        r["tier"] = tier
        prev = r["vorp"]

    os.makedirs("data", exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(pool, f, indent=1)

    # Userscript BOARD format: [rank, name, pos, team, bye, tier, adp]
    js_rows = [
        [r["rank"], r["name"], r["pos"], r["team"], r["bye"], r["tier"], r["adp"] or 999]
        for r in pool
    ]
    board_line = "const BOARD = " + json.dumps(js_rows) + ";"
    with open(OUT_JS, "w") as f:
        f.write("// Generated by src/build_board.py — do not edit by hand\n")
        f.write(f"// Source: Sleeper 2026 projections+ADP, {len(pool)} players, 0.5 PPR VORP-ranked\n")
        f.write(board_line + "\n")

    # Push so Tampermonkey @require (GitHub raw) picks up new board
    subprocess.run(["git", "add", OUT_JS, OUT_JSON], check=True)
    subprocess.run(
        ["git", "commit", "-q", "-m", "Refresh draft board from Sleeper"], check=False
    )
    subprocess.run(["git", "push", "-q"], check=True)
    print("Pushed board to GitHub — reload draft page to pick up (no re-paste)")

    print(f"Wrote {OUT_JSON} and {OUT_JS} ({len(pool)} players)")
    print("\nTop 15:")
    for r in pool[:15]:
        print(f"  {r['rank']:>3} {r['name']:<24} {r['pos']:<3} {r['team']:<4} "
              f"proj={r['proj']:<6} adp={r['adp']} vorp={r['vorp']}")


if __name__ == "__main__":
    main()
